runs:
  dir: "./runs"
dataset:
  name: "cifar10"
  path: "./data/cifar10"
kpi:
  - name: "tps"
    unit: "ms"
    fqn: "Time per step"
  - name: "acc_train"
    unit: "%"
    fqn: "Training Accuracy"
  - name: "train_loss"
    unit: ""
    fqn: "Train Loss"
  - name: "gpu_mem"
    unit: "GB"
    fqn: "GPU Memory usage"
lr_scheduler:
  type: "CosineAnnealingLR"
  step: 30
  gamma: 0.1
Apollo:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
Adam:
  lr: 0.01
  beta1: 0.9
  beta2: 0.999
  eps: 0.0001
  weight_decay: 0
AdaHessian:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
AdaBelief:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
AdamW:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
RMSProp:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
SGD:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
