runs:
  epochs: 100
  name: "cifar10-hessian-approx"
  dir: "./runs"
  lr_schedule_per_epoch: True
dataset:
  name: "cifar10"
  path: "./data/cifar10"
kpi:
  - name: "tps"
    unit: "ms"
    fqn: "Time per step"
    plot: "box"
  - name: "ttc"
    unit: "epochs"
    fqn: "Time till convergence"
    plot: "graph"
  - name: "acc_train"
    unit: "%"
    fqn: "Training Accuracy"
    plot: "graph"
  - name: "acc_test"
    unit: "%"
    fqn: "Test Accuracy"
    plot: "graph"
  - name: "test_loss"
    unit: ""
    fqn: "Test Loss"
    plot: "graph"
  - name: "train_loss"
    unit: ""
    fqn: "Train Loss"
    plot: "graph"
  - name: "gpu_mem"
    unit: "MB"
    fqn: "GPU Memory usage"
    plot: "box"
lr_scheduler:
  type: "MultiStepLR"
  params:
    milestones: [40,80]
    gamma: 0.1
optim:
  Apollo:
    name: "Apollo"
    params:
      init_lr: "None"
      lr: 0.01
      eps: 0.0001
      beta: 0.9
      warmup: 500
      weight_decay_type: "L2"
      weight_decay: 0
      rebound: "constant"
  ApolloW:
    name: "Apollo"
    params:
      init_lr: "None"
      lr: 0.01
      eps: 0.0001
      beta: 0.9
      warmup: 500
      weight_decay_type: "decoupled"
      weight_decay: 0.025
      rebound: "constant"
  Adam:
    name: "Adam"
    params:
      lr: 0.001
      beta1: 0.9
      beta2: 0.999
      eps: 0.00000001
      weight_decay: 0
  AdaHessian:
    name: "AdaHessian"
    params:
      lr: 0.15
      beta1: 0.9
      beta2: 0.999
      eps: 0.01
      weight_decay: 0
      init_lr: 0.001
      hessian_power: 1.0
      update_each: 1
      warmup: 500
  AdaBelief:
    name: "AdaBelief"
    params:
      lr: 0.001
      beta1: 0.9
      beta2: 0.999
      eps: 0.0000000001
      weight_decay: 0
  AdamW:
    name: "Adam"
    params:
      lr: 0.0005
      beta1: 0.9
      beta2: 0.98
      eps: 0.000000001
      weight_decay: 0
      weight_decouple: True
  RMSprop:
    name: "RMSprop"
    params:
      lr: 0.001
      alpha: 0.99
      eps: 0.00000001
      weight_decay: 0.00025
  SGD:
    name: "SGD"
    params:
      lr: 0.1
      momentum: 0
      weight_decay: 0.00025
