runs:
  epochs: 8
  name: "wmt14"
  dir: "./runs"
  lr_schedule_per_epoch: True
dataset:
  name: "wmt14"
  path: "./data/wmt14"
kpi:
  - name: "tps"
    unit: "ms"
    fqn: "Time per step"
    plot: "box"
  - name: "ttc"
    unit: "epochs"
    fqn: "Time till convergence"
    plot: "graph"
  - name: "acc_train"
    unit: "%"
    fqn: "Training Accuracy"
    plot: "graph"
  - name: "acc_test"
    unit: "%"
    fqn: "Test Accuracy"
    plot: "graph"
  - name: "test_loss"
    unit: ""
    fqn: "Test Loss"
    plot: "graph"
  - name: "train_loss"
    unit: ""
    fqn: "Train Loss"
    plot: "graph"
  - name: "gpu_mem"
    unit: "MB"
    fqn: "GPU Memory usage"
    plot: "box"
  - name: "bleu"
    unit: ""
    fqn: "BLEU Score"
    plot: "graph"
  - name: "cosine_sim"
    unit: ""
    fqn: "Cosine Similarity"
    plot: "box"
  - name: "nmse"
    unit: ""
    fqn: "NMSE"
    plot: "box"
lr_scheduler:
  type: "-"
optim:
  Apollo:
    name: "Apollo"
    params:
      init_lr: "None"
      lr: 0.01
      eps: 0.0001
      beta: 0.9
      warmup: 500
      weight_decay_type: "L2"
      weight_decay:  0.0001
      rebound: "constant"
  ApolloW:
    name: "Apollo"
    params:
      init_lr: "None"
      lr: 0.01
      eps: 0.0001
      beta: 0.9
      warmup: 500
      weight_decay_type: "decoupled"
      weight_decay: 0.01
      rebound: "constant"
  AdaHessian:
    name: "AdaHessian"
    params:
      lr: 0.15
      beta1: 0.9
      beta2: 0.999
      eps: 0.01
      weight_decay: 0.001
      init_lr: 0.001
      hessian_power: 1.0
      update_each: 1
      warmup: 500
  Adam:
    name: "Adam"
    params:
      lr: 0.0005
      beta1: 0.9
      beta2: 0.98
      eps: 0.000000001
      weight_decay: 0
  AdamW:
    name: "Adam"
    params:
      lr: 0.0005
      beta1: 0.9
      beta2: 0.98
      eps: 0.000000001
      weight_decay: 0.0001
      weight_decouple: True

  AdaBelief:
    name: "AdaBelief"
    params:
      lr: 0.0005
      beta1: 0.9
      beta2: 0.999
      eps:  0.000000001
      weight_decay: 0.0001
      weight_decouple: True

  RMSprop:
    name: "RMSprop"
    params:
      lr: 0.001
      alpha: 0.99
      eps: 0.00000001
      weight_decay: 0.0001
  SGD:
    name: "SGD"
    params:
      lr: 0.005
      momentum: 0.9
      weight_decay: 0


#this will train the optims with all their optimal values
