runs:
  name: "test"
  dir: "./runs"
dataset:
  name: "cifar10"
  path: "./data/cifar10"
kpi:
  - name: "tps"
    unit: "ms"
    fqn: "Time per step"
    plot: "box"
  - name: "ttc"
    unit: "epochs"
    fqn: "Time till convergence"
    plot: "graph"
  - name: "acc_train"
    unit: "%"
    fqn: "Training Accuracy"
    plot: "graph"
  - name: "acc_test"
    unit: "%"
    fqn: "Test Accuracy"
    plot: "graph"
  - name: "train_loss"
    unit: ""
    fqn: "Train Loss"
    plot: "graph"
  - name: "gpu_mem"
    unit: "MB"
    fqn: "GPU Memory usage"
    plot: "box"
lr_scheduler:
  type: "-"
  step: 2000
  gamma: 0.1
Apollo:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
Adam:
  lr: 0.001
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  weight_decay: 0
AdaHessian:
  lr: 0.1
  beta1: 0.9
  beta2: 0.999
  eps: 0.0001
  weight_decay: 0
  init_lr: 0.0
  hessian_power: 1.0
  update_each: 1
  warmup: 0
AdaBelief:
  lr: 0.01
  beta1: 0.9
  beta2: 0.999
  eps: 0.0001
  weight_decay: 0
AdamW:
  lr: 0.001
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  weight_decay: 0
RMSprop:
  lr: 0.01
  alpha: 0.99
  eps: 0.00000001
  weight_decay: 0
SGD:
  lr: 0.01
  momentum: 0
  weight_decay: 0
