dataset:
  name: "cifar10"
  path: "./data/cifar10"
Apollo:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
Adam:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
AdaHessian:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
AdaBelief:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
AdamW:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
RMSProp:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
SGD:
  init_lr: "None"
  lr: 0.01
  eps: 0.0001
  beta: 0.9
  warmup: 500
  weight_decay_type: "None"
  weight_decay: 0
  rebound: "constant"
