name: Run Tests
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy torch

      - name: Run All Test Files Matching *.test.py
        run: |
          for test_file in $(find tests -name "*.test.py"); do
            python3 "$test_file"
          done
